"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

#fromat = """$all"""

format = """
$battery\
$os\
$container\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$aws\
$azure\
$gcloud\
$time\
$line_break\
$jobs\
$cmd_duration\
$shlvl\
$character
"""
[battery]

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[[battery.display]]
threshold = 60
style = 'bold light green'

[os]
disabled = false

[os.symbols]
AIX = " "
Alpaquita = " "
AlmaLinux = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = "󰣠 "
Emscripten = "󰣠 "
EndeavourOS = " "
Fedora = " "
FreeBSD = "󰣠 "
Garuda = " "
Gentoo = "󰣨 "
HardenedBSD = "󰣠 "
Illumos = " "
Kali = " "
Linux = " "
Mabox = "󰣠 "
Macos = "󰀵 "
Manjaro = "󱘊 "
Mariner = " "
MidnightBSD = "󰣠 "
Mint = "󰣭 "
NetBSD = "󰣠 "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = "󰅟 "
openEuler = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = "󰐿 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
RockyLinux = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = "󰣛 "
Unknown = "? "
Uos = " "
Void = "  "
Windows = " "

[container]

[username]
show_always = true
format='[$user]($style)'

[hostname]
ssh_only = false
format='@[$hostname]($style) '

[directory]
truncation_length = 2
truncation_symbol = '…/'

#[directory.substitutions]
#"Documents" = "󰈙 "
#"Downloads" = " "
#"Music" = "󰝚 "
#"Pictures" = " "
#"Developer" = "󰲋 "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[aws]
#format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
format = '[$symbol($profile)]($style) '
symbol = ' '

[azure]
format = '[$symbol($subscription)]($style) '
symbol = ' '

[gcloud]
#format = '[$symbol$account(@$domain)(\($region\))]($style) '
format = '[$symbol$account(@$domain)]($style) '
symbol = ' '
detect_env_vars = ['CLOUDSDK_CONFIG', 'CLOUDSDK_ACTIVE_CONFIG_NAME']

[time]
disabled = false
time_format = "%R"
format = '[$time]($style) '
style = 'bold green'

[line_break]
disabled = true

[jobs]

[cmd_duration]
format = '[$duration]($style) '

[shlvl]
disabled = false
format = '[$symbol]($style)'
repeat = true
symbol = '❯'
repeat_offset = 1
threshold = 0

[character]

